In [77]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [78]:
data=pd.read_csv('missing_value_free.csv')
data.drop(columns=['Unnamed: 0','CPU Name','GPU Name','OS'],axis=1,inplace=True)
data

,Brand,CPU Mark,GPU Mark,Monitor,Width,Height,RAM,Storage Amount,Price,Weight
0,MSI,26454.0,7320.0,15.6,1920.0,1080.0,16384.0,2097152.0,1529.00,3.03
1,Dell,34306.0,19560.0,15.6,1366.0,768.0,16384.0,4096000.0,2308.81,3.64
2,Dell,3642.0,4253.0,14.0,1920.0,1080.0,8192.0,262144.0,614.99,1.23
3,Dell,19333.0,2690.0,16.0,1920.0,1200.0,24576.0,1048576.0,1079.00,1.58
4,Dell,28003.0,8274.0,15.6,1920.0,1200.0,32768.0,1048576.0,1907.00,1.92
...,...,...,...,...,...,...,...,...,...,...
3963,HP,15287.0,2690.0,15.6,1920.0,1080.0,49152.0,2097152.0,1129.99,1.82
3964,HP,1556.0,1476.0,14.0,1366.0,768.0,4096.0,131072.0,197.00,1.45
3965,Acer,13554.0,4253.0,14.0,2560.0,1600.0,16384.0,524288.0,1099.99,1.45
3966,Lenovo,26454.0,7320.0,16.0,1920.0,1200.0,16384.0,524288.0,1289.00,1.45
3967,Lenovo,10280.0,2690.0,15.6,1920.0,1080.0,12288.0,1048576.0,629.00,1.45

In [79]:
import pickle
import pickle
def encode(brand): 
    LabelEncoder_brands = LabelEncoder()
    LabelEncoder_brands.fit(data['Brand'])
    return LabelEncoder_brands.transform([brand])[0]
data['Encoded_Brand'] = data['Brand'].apply(encode)
price_column = data.pop('Price')
data['Price'] = price_column
encoded_brand_dict = dict(zip(data['Brand'],data['Encoded_Brand']))
# Specify the file path to save the dictionary
file_path = 'encoded_brand_dict.pkl'

# Save the dictionary to the file
with open(file_path, 'wb') as file:
    pickle.dump(encoded_brand_dict, file)
    # Specify the file path to load the dictionary
file_path = 'encoded_brand_dict.pkl'

print(len(encoded_brand_dict))

print(encoded_brand_dict)
data

41
{'MSI': 23, 'Dell': 11, 'Asus': 4, 'Lenovo': 21, 'Core Innovations': 9, 'Acer': 1, 'LG': 20, 'HP': 16, 'Samsung': 31, 'GIGABYTE': 12, 'Apple': 3, 'Panasonic': 27, 'XAMMUE': 37, 'Microsoft': 25, 'ROKC': 28, 'Best Notebooks': 8, 'SGIN': 30, 'Best Notebook': 7, 'Goldengulf': 15, 'HUNSN': 17, 'Razer': 29, 'Gateway': 14, 'Toshiba': 35, 'Luqeeg': 22, 'ONN': 26, 'Mavark': 24, 'Yoga Notebook': 38, 'WEELIAO': 36, 'Adata': 2, 'thunderb': 40, 'Best 2 in 1 Laptop': 6, 'IVIEW': 19, 'IST Computers': 18, 'BINTEC': 5, 'Corsair': 10, 'Thomson': 33, 'GPDBRANDSTORE': 13, 'aichiw': 39, 'TechDeal': 32, 'Tocosy': 34, 'AWOW': 0}

,Brand,CPU Mark,GPU Mark,Monitor,Width,Height,RAM,Storage Amount,Weight,Encoded_Brand,Price
0,MSI,26454.0,7320.0,15.6,1920.0,1080.0,16384.0,2097152.0,3.03,23,1529.00
1,Dell,34306.0,19560.0,15.6,1366.0,768.0,16384.0,4096000.0,3.64,11,2308.81
2,Dell,3642.0,4253.0,14.0,1920.0,1080.0,8192.0,262144.0,1.23,11,614.99
3,Dell,19333.0,2690.0,16.0,1920.0,1200.0,24576.0,1048576.0,1.58,11,1079.00
4,Dell,28003.0,8274.0,15.6,1920.0,1200.0,32768.0,1048576.0,1.92,11,1907.00
...,...,...,...,...,...,...,...,...,...,...,...
3963,HP,15287.0,2690.0,15.6,1920.0,1080.0,49152.0,2097152.0,1.82,16,1129.99
3964,HP,1556.0,1476.0,14.0,1366.0,768.0,4096.0,131072.0,1.45,16,197.00
3965,Acer,13554.0,4253.0,14.0,2560.0,1600.0,16384.0,524288.0,1.45,1,1099.99
3966,Lenovo,26454.0,7320.0,16.0,1920.0,1200.0,16384.0,524288.0,1.45,21,1289.00
3967,Lenovo,10280.0,2690.0,15.6,1920.0,1080.0,12288.0,1048576.0,1.45,21,629.00

In [80]:
data.to_csv('new_preprocess.csv',index=False)